### ISSUE TITLE
No memory slot

### ISSUE THREAD

**Issue by MisterMax82** [nadavshemesh/silver-reversing-sct#2]
Hi BRO
Following [your guide](https://github.com/nadavshemesh/silver-hacks/issues/1) I created and played with GRANPA without any problem **as a condition** of removing it (var old_grandad = call get_char_handle(int 393216) call remove_char(var old_grandad)) from exbarrac.
If it is not removed we have this error ((I have not added any other characters (David and Grandpa only):
![2022-09-27](https://user-images.githubusercontent.com/113446337/192530175-311c4a0b-3d79-4355-aaef-f3b70ba3ec22.png)
I then tried changing various characters: Frink, oldwoman, buzuki, Nemesis, Viviene and many others but always the same error. Es: call create_char(var &init_position, "hnemesis", int 35, int 13) or call create_char(var &init_position, "hbuzuki", int 35, int 13) under ._onload .

what do I do then?
I try to remove Granda. And what happens? I enter the level but then (rightly) the enemies not finding our beloved Granda as a target, crash the game.
So is the problem that level that doesn't accept more than 2 characters or am I doing something wrong? (much more probable)
Help me 
Ps: Are you going to make a scrip for Cheat engine that creates characters? ha ha for people who are impeded like me.
Keep going with this project that is great

**Comment by nadavshemesh** [comment]
Yes, as i mentioned before, theres a character limit. (Im not entirely sure what it is but it seems to be around 10-15)
the level i gave as an example (exbarrac) is filled with enemies so either try to
* remove some enemies by commenting or deleting the lines of code creating them (i.e call create_enemy ...).
* create extra playable characters on a different level where there arent as many characters/ enemies.

I'm planning to make that feature as a hack in the [silver-hacks](https://github.com/nadavshemesh/silver-hacks) project but unfortunately due to my recent schedule its not likely to be anytime soon.

let me know if it helped.

**Comment by MisterMax82** [comment]
Hi
yes , I tried removing the string ; call create_enemy and the various references but the game exits directly to windows. I will look forward to the scripts on cheat engine which are easier for me. 
I noticed that if I summon the character to the first level, the game runs without a problem, but if I create it with the string "call create ...." the game crashes. I don't know.

**Comment by nadavshemesh** [comment]
Alright, since this isnt an issue with the tool itself but rather with handling the game's code, I'm closing this one.

I suggest playing around with the code to get an idea of what works and what doesnt, I know its tough that the game doesnt always indicate what exactly went wrong so it requires patience and dedication to figure out sometimes.
I hope you'll manage to accomplish the type of modifications you want :) good luck.
